export default function Page() {
  return (
    <main>
      <nav className="nav">
        <strong>Example Forge Site</strong>
        <div><a href="/">Home</a>
        <a href="/about">About</a>
        <a href="/projects">Projects</a>
        <a href="/signals">Signals</a>
        <a href="/presentation">Presentation</a>
        <a href="/proof">Proof</a>
        <a href="/contact">Contact</a></div>
      </nav>
      
      <section className="hero">
        <p className="eyebrow">Generated by AndyAI Website Forge</p>
        <h1>A website that knows its story before it becomes pages.</h1>
        <p>Generated from a controlled blueprint, content pack and route pack through AndyAI Website Forge.</p>
        <div className="actions"><a href="/presentation">Explore the system</a><a href="/proof">View generated proof</a></div>
      </section>
      <section className="grid">
        <section className="panel"><h2>Story → Structure → Visuals → Proof</h2><p>Website Forge turns raw project intent into a structured public artifact with clear sections, route logic, visual slots and verification evidence.</p></section>
        <section className="panel"><h2>Controlled production, not random page making</h2><p>Every generated page should come from declared input packs, not from accidental copy-paste or invisible decisions.</p></section>
        <section className="panel"><h2>Human-approved website factory</h2><p>The system supports human judgment by packaging structure, consistency and QA into a repeatable flow.</p></section>
      </section>
      <section><h2>Visual Slots</h2><div className="grid"><article className="visualSlot"><p>Hero visual</p><strong>Explain the core site story</strong><span>16:9</span></article>
          <article className="visualSlot"><p>System flow visual</p><strong>Show blueprint to site generation flow</strong><span>4:3</span></article></div></section>
      <section><h2>CTA Blocks</h2><div className="grid"><article className="card"><h3>Generate next site</h3><p>Use the forge to turn a controlled content pack into a public artifact.</p></article>
          <article className="card"><h3>Review evidence</h3><p>Open the generated evidence file before committing or deploying.</p></article></div></section>

    </main>
  );
}
