#!/usr/bin/env bash
set -euo pipefail
SITE_DIR="${1:-generated-sites/example-forge-site}"
PASS=0
FAIL=0
check_file(){ if [ -f "$SITE_DIR/$1" ]; then echo "🟢 exists: $1"; PASS=$((PASS+1)); else echo "🔴 missing: $1"; FAIL=$((FAIL+1)); fi; }
check_absent(){ if [ ! -e "$SITE_DIR/$1" ]; then echo "🟢 absent: $1"; PASS=$((PASS+1)); else echo "🔴 forbidden present: $1"; FAIL=$((FAIL+1)); fi; }
check_contains(){ if grep -R "$2" "$SITE_DIR/$1" >/dev/null 2>&1; then echo "🟢 keyword present in $1: $2"; PASS=$((PASS+1)); else echo "🔴 keyword missing in $1: $2"; FAIL=$((FAIL+1)); fi; }

[ -d "$SITE_DIR" ] || { echo "🔴 missing site dir: $SITE_DIR"; exit 1; }
check_file README.md
check_file package.json
check_file next.config.js
check_file tsconfig.json
check_file next-env.d.ts
check_file app/layout.tsx
check_file app/page.tsx
check_file app/globals.css
check_file app/about/page.tsx
check_file app/contact/page.tsx
check_file app/presentation/page.tsx
check_file app/projects/page.tsx
check_file app/signals/page.tsx
check_file app/proof/page.tsx
check_file public/visuals/.gitkeep
check_file docs/SITE_GENERATION_EVIDENCE.md
check_file docs/CONTENT_ROUTE_PACK_EVIDENCE.md
check_absent .env
check_absent .env.local
check_absent .next
check_absent node_modules
check_contains README.md "Generated by AndyAI Website Forge PACK3"
check_contains docs/CONTENT_ROUTE_PACK_EVIDENCE.md "Generated routes"
check_contains app/page.tsx "Visual Slots"
check_contains app/projects/page.tsx "project"
check_contains app/signals/page.tsx "signal"
check_contains app/proof/page.tsx "Generation Proof"

echo "PASS=$PASS FAIL=$FAIL"
if [ "$FAIL" -ne 0 ]; then echo "🔴 generated-site verification failed"; exit 1; fi
echo "🟢 generated-site verification passed"
